-- Jalankan sekali di Supabase SQL Editor untuk mengaktifkan fitur shift kasir.

alter table if exists public.cash_bank_transactions
  add column if not exists approval_status text not null default 'approved';

alter table if exists public.cash_bank_transactions
  add column if not exists approved_by text;

create table if not exists public.cash_shifts (
  id bigint generated by default as identity primary key,
  cashier_name text not null,
  shift_name text not null default 'Shift utama',
  opening_cash numeric(12, 2) not null check (opening_cash >= 0),
  opened_at timestamptz not null default now(),
  closing_cash numeric(12, 2),
  expected_cash numeric(12, 2),
  difference numeric(12, 2),
  closed_at timestamptz,
  status text not null default 'open' check (status in ('open', 'closed'))
);

create index if not exists cash_shifts_status_idx
  on public.cash_shifts(status);

alter table public.cash_shifts enable row level security;

notify pgrst, 'reload schema';
