-- Jalankan file ini di Supabase SQL Editor.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Makanan',
  price numeric(12, 2) not null check (price >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  menu_item_id bigint not null references public.menu_items(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  total_amount numeric(12, 2) generated always as (quantity * unit_price) stored,
  payment_method text not null default 'Cash' check (payment_method in ('Cash', 'Transfer', 'QRIS')),
  sale_date timestamptz not null default now(),
  voided_at timestamptz,
  voided_by text,
  void_reason text
);
alter table public.sales add column if not exists voided_at timestamptz;
alter table public.sales add column if not exists voided_by text;
alter table public.sales add column if not exists void_reason text;

create table if not exists public.cash_bank_transactions (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete set null,
  transaction_type text not null check (transaction_type in ('Income', 'Expense')),
  account text not null default 'Kas' check (account in ('Kas', 'Bank')),
  category text not null default 'Lainnya',
  amount numeric(12, 2) not null check (amount > 0),
  note text,
  transaction_date timestamptz not null default now()
);

alter table public.cash_bank_transactions add column if not exists approval_status text not null default 'approved' check (approval_status in ('pending', 'approved', 'rejected'));
alter table public.cash_bank_transactions add column if not exists approved_by text;
alter table public.cash_bank_transactions add column if not exists receipt_path text;
alter table public.cash_bank_transactions add column if not exists voided_at timestamptz;
alter table public.cash_bank_transactions add column if not exists voided_by text;
alter table public.cash_bank_transactions add column if not exists void_reason text;
alter table public.cash_bank_transactions add column if not exists transaction_role text not null default 'operating';
alter table public.cash_bank_transactions add column if not exists reconciliation_status text not null default 'unmatched';

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('cash-receipts', 'cash-receipts', false, 2097152, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = false, file_size_limit = 2097152, allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.cash_closings (
  id bigint generated by default as identity primary key,
  cashier_name text not null,
  actual_cash numeric(12, 2) not null check (actual_cash >= 0),
  expected_cash numeric(12, 2),
  difference numeric(12, 2),
  note text,
  closed_at timestamptz not null default now()
);
create index if not exists cash_closings_closed_at_idx on public.cash_closings(closed_at desc);
alter table public.cash_closings enable row level security;

create table if not exists public.bank_reconciliations (
  id bigint generated by default as identity primary key,
  statement_date date not null,
  app_balance numeric(12, 2) not null,
  statement_balance numeric(12, 2) not null,
  difference numeric(12, 2) not null,
  note text,
  actor text not null,
  created_at timestamptz not null default now()
);
alter table public.bank_reconciliations enable row level security;

create table if not exists public.sync_operations (
  op_id text primary key,
  result jsonb,
  created_at timestamptz not null default now()
);
alter table public.sync_operations enable row level security;

create table if not exists public.debts (
  id bigint generated by default as identity primary key,
  debt_type text not null check (debt_type in ('receivable', 'payable')),
  party_name text not null,
  description text not null,
  original_amount numeric(12, 2) not null check (original_amount > 0),
  remaining_amount numeric(12, 2) not null check (remaining_amount >= 0),
  due_date date,
  status text not null default 'open' check (status in ('open', 'partial', 'paid')),
  account text not null default 'Kas' check (account in ('Kas', 'Bank')),
  created_at timestamptz not null default now(),
  settled_at timestamptz
);
alter table public.debts add column if not exists offline_id text unique;
alter table public.debts enable row level security;

create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  category text not null,
  period_month date not null,
  amount numeric(12, 2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  unique (category, period_month)
);
alter table public.budgets enable row level security;

create table if not exists public.recurring_expenses (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Operasional',
  account text not null default 'Kas' check (account in ('Kas', 'Bank')),
  amount numeric(12, 2) not null check (amount > 0),
  frequency text not null default 'monthly' check (frequency in ('weekly', 'monthly')),
  next_due date not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.recurring_expenses enable row level security;
alter table public.app_settings enable row level security;

insert into public.app_settings (key, value)
values ('minimum_cash_balance', '100000')
on conflict (key) do nothing;

alter table public.menu_items add column if not exists code text;
alter table public.menu_items add column if not exists image_url text;
alter table public.menu_items add column if not exists is_favorite boolean not null default false;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text,
  reason text,
  actor text not null default 'Kasir',
  created_at timestamptz not null default now(),
  details jsonb
);
alter table public.audit_logs add column if not exists details jsonb;

create table if not exists public.combos (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12, 2) not null check (price > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.combo_items (
  id bigint generated by default as identity primary key,
  combo_id bigint not null references public.combos(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id),
  quantity integer not null default 1 check (quantity > 0)
);

alter table public.audit_logs enable row level security;
alter table public.combos enable row level security;
alter table public.combo_items enable row level security;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  order_type text not null default 'takeaway' check (order_type in ('dine-in', 'takeaway', 'delivery')),
  table_number text,
  status text not null default 'paid' check (status in ('open', 'paid', 'void', 'refunded')),
  subtotal numeric(12, 2) not null check (subtotal >= 0),
  discount_type text not null default 'none' check (discount_type in ('none', 'percent', 'amount')),
  discount_value numeric(12, 2) not null default 0 check (discount_value >= 0),
  tax_percent numeric(5, 2) not null default 0 check (tax_percent >= 0),
  service_percent numeric(5, 2) not null default 0 check (service_percent >= 0),
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  cashier_name text not null default 'Kasir',
  created_at timestamptz not null default now()
);
alter table public.orders add column if not exists source text not null default 'walk_in';
alter table public.orders add column if not exists platform_fee numeric(12, 2) not null default 0;
alter table public.orders add column if not exists kitchen_status text not null default 'open';

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  special_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  method text not null check (method in ('Cash', 'QRIS', 'Transfer', 'E-Wallet', 'Debit', 'Credit')),
  amount numeric(12, 2) not null check (amount > 0),
  cash_received numeric(12, 2),
  change_amount numeric(12, 2) not null default 0 check (change_amount >= 0),
  created_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists payments_order_id_idx on public.payments(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;

create index if not exists sales_sale_date_idx on public.sales(sale_date desc);
create index if not exists cash_bank_transaction_date_idx on public.cash_bank_transactions(transaction_date desc);

alter table public.menu_items enable row level security;
alter table public.sales enable row level security;
alter table public.cash_bank_transactions enable row level security;

-- Backend memakai service role key. Jangan expose key tersebut ke browser.

insert into public.menu_items (name, category, price)
select * from (values
  ('Nasi Goreng', 'Makanan', 18000::numeric),
  ('Ayam Geprek', 'Makanan', 22000::numeric),
  ('Es Teh Manis', 'Minuman', 6000::numeric),
  ('Kopi Susu', 'Minuman', 12000::numeric)
) as seed(name, category, price)
where not exists (select 1 from public.menu_items);